stages:
  - build

build:
  stage: build
  image: eclipse-temurin:17
  variables:
    JAVA_FX_HOME: /usr/share/openjfx/lib
  before_script:
    - apt-get update
    - apt-get install -y ant openjfx unzip wget
  script:
    - ant